name: Send Price Report

on:
  schedule:
    - cron: '0 0 * * *'      # 07:00 VN (UTC+7) = 0:00 UTC
    - cron: '20 2 * * *'     # 09:20 VN (UTC+7) = 2:20 UTC
    - cron: '0 5 * * *'      # 12:00 VN (UTC+7) = 5:00 UTC
    - cron: '0 9 * * *'      # 16:00 VN (UTC+7) = 9:00 UTC
    - cron: '0 11 * * *'     # 18:00 VN (UTC+7) = 11:00 UTC
  workflow_dispatch:        

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run price bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py