name: Send Price Report

on:
  schedule:
    - cron: '36 7 * * *'      # 14:36 VN (UTC+7) = 7:36 UTC
    - cron: '38 7 * * *'      # 14:38 VN (UTC+7) = 7:38 UTC
    - cron: '40 7 * * *'      # 14:40 VN (UTC+7) = 7:40 UTC
    - cron: '42 7 * * *'      # 14:42 VN (UTC+7) = 7:42 UTC
  workflow_dispatch:        

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run price bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py