name: Send Price Report

on:
  schedule:
    - cron: '41 8 * * *'      # 15:41 VN (UTC+7) = 8:41 UTC
    - cron: '43 8 * * *'      # 15:43 VN (UTC+7) = 8:43 UTC
    - cron: '45 8 * * *'      # 15:45 VN (UTC+7) = 8:45 UTC
    - cron: '47 8 * * *'      # 15:47 VN (UTC+7) = 8:47 UTC
  workflow_dispatch:        

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Show current time
        run: date

      - name: Run price bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py