name: Send Price Report

on:
  schedule:
    - cron: '0 0 * * *'      # 07:00 VN (UTC+7) = 0:00 UTC
    - cron: '30 4 * * *'     # 11:30 VN (UTC+7) = 4:30 UTC
    - cron: '30 11 * * *'    # 18:30 VN (UTC+7) = 11:30 UTC
    - cron: '50 6 * * *'     # 13:50 VN (UTC+7) = 6:50 UTC
    - cron: '52 6 * * *'     # 13:52 VN (UTC+7) = 6:52 UTC
    - cron: '54 6 * * *'     # 13:54 VN (UTC+7) = 6:54 UTC
  workflow_dispatch:         # Cho phép chạy thủ công

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run price bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py