name: Send Price Report

on:
  schedule:
    - cron: '59 7 * * *'      # 14:59 VN (UTC+7) = 7:59 UTC
    - cron: '0 8 * * *'      # 15:00 VN (UTC+7) = 8:00 UTC
    - cron: '2 8 * * *'      # 15:02 VN (UTC+7) = 8:02 UTC
    - cron: '4 8 * * *'      # 15:04 VN (UTC+7) = 8:04 UTC
  workflow_dispatch:        

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Show current time
        run: date

      - name: Run price bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py