name: Send Price Report

on:
  schedule:
    - cron: '*/3 * * * *'      # Chạy mỗi 3 phút để test
  workflow_dispatch:        

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run price bot
        env:
          TELEGRAM_BOT_TOKEN: 7743584914:AAF_oFNuFWlmId9yKP0-5SN0JnR-KT6GhRs
          TELEGRAM_CHAT_ID: 6794790211
        run: |
          python main.py