name: Send Price Report

on:
  schedule:
    - cron: '16 7 * * *'      # 14:16 VN (UTC+7) = 7:16 UTC
    - cron: '18 7 * * *'      # 14:18 VN (UTC+7) = 7:18 UTC
    - cron: '20 7 * * *'      # 14:20 VN (UTC+7) = 7:20 UTC
    - cron: '22 7 * * *'      # 14:22 VN (UTC+7) = 7:22 UTC
  workflow_dispatch:        

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run price bot
        env:
          TELEGRAM_BOT_TOKEN: 7743584914:AAF_oFNuFWlmId9yKP0-5SN0JnR-KT6GhRs
          TELEGRAM_CHAT_ID: 6794790211
        run: |
          python main.py